### ISSUE TITLE
RHAMT execution failed due to: No services of type [org.jboss.windup.config.metadata.RuleProviderRegistryCache] could be found in any started addons.

### ISSUE THREAD

**Issue by tarunkg** [RedHat-Middleware-Workshops/modernize-apps-katacoda#26]
RHAMT command line failing at Windows 10;

C:\Tarun\Installable\migrationtoolkit-rhamt-cli-4.2.1-offline\rhamt-cli-4.2.1.Final\bin>./rhamt-cli --input C:\Users\TARUNKUMAR\Downloads\simple-sample-app.ear --output c:\tarun\ --source weblogic --target eap:7 --packages com.acme
'.' is not recognized as an internal or external command,
operable program or batch file.

C:\Tarun\Installable\migrationtoolkit-rhamt-cli-4.2.1-offline\rhamt-cli-4.2.1.Final\bin>rhamt-cli --input C:\Users\TARUNKUMAR\Downloads\simple-sample-app.ear --output c:\tarun\ --source weblogic --target eap:7 --packages com.acme
Using RHAMT at C:\Tarun\Installable\migrationtoolkit-rhamt-cli-4.2.1-offline\rhamt-cli-4.2.1.Final\bin\..
Using Java at C:\Program Files\Java\jdk1.8.0_231
> Red Hat Application Migration Toolkit (RHAMT) CLI, version 4.2.1.Final.

Red Hat Application Migration Toolkit (RHAMT) CLI, version [  ] - by Red Hat, Inc. [ https://developers.redhat.com/products/rhamt/overview/ ]

WARNING: Unrecognized command-line argument: --input
FATAL: Furnace Addon repository path:
ROOT_df010052-f4ad-4d95-82b1-affc85441767
---REPOSITORIES---
C:\Users\TARUNKUMAR\.rhamt\.addons

---ADDONS---

---GRAPH VIEW---

WARNING: Unrecognized command-line argument: C:\Users\TARUNKUMAR\Downloads\simple-sample-app.ear
WARNING: Unrecognized command-line argument: --output
FATAL: Furnace Addon repository path:
ROOT_df010052-f4ad-4d95-82b1-affc85441767
---REPOSITORIES---
C:\Users\TARUNKUMAR\.rhamt\.addons

---ADDONS---

---GRAPH VIEW---

WARNING: Unrecognized command-line argument: c:\tarun" --source weblogic --target eap:7 --packages com.acme --immutableAddonDir C:\Tarun\Installable\migrationtoolkit-rhamt-cli-4.2.1-offline\rhamt-cli-4.2.1.Final\bin\..\addons
RHAMT execution failed due to: No services of type [org.jboss.windup.config.metadata.RuleProviderRegistryCache] could be found in any started addons.
org.jboss.forge.furnace.exception.ContainerException: No services of type [org.jboss.windup.config.metadata.RuleProviderRegistryCache] could be found in any started addons.
        at org.jboss.forge.furnace.impl.addons.ImportedImpl.get(ImportedImpl.java:79)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback$2.call(ClassLoaderAdapterCallback.java:124)
        at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
        at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback.invoke(ClassLoaderAdapterCallback.java:97)
        at org.jboss.forge.furnace.services.Imported_$$_jvstce8_9.get(Imported_$$_jvstce8_9.java)
        at org.jboss.windup.bootstrap.commands.windup.RunWindupCommand.runWindup(RunWindupCommand.java:168)
        at org.jboss.windup.bootstrap.commands.windup.RunWindupCommand.execute(RunWindupCommand.java:67)
        at org.jboss.windup.bootstrap.Bootstrap.executePhase(Bootstrap.java:520)
        at org.jboss.windup.bootstrap.Bootstrap.run(Bootstrap.java:340)
        at org.jboss.windup.bootstrap.Bootstrap.main(Bootstrap.java:106)

**************************
echo %JAVA_HOME%
C:\Program Files\Java\jdk1.8.0_231

********************************

**Comment by tarunkg** [comment]
I request anyone help. I need to resolve as matter of urgency. Please do also know if you need any more information .

**Comment by fabras78** [comment]
I don't know on Windows but I have had the same errors on mac. I installed adoptopenjdk-8 and set the JAVA_HOME.

$ brew cask install adoptopenjdk8
$ export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)

hope this help in such a way

**Comment by jamesfalkner** [comment]
This is not a bug in the workshop that this repository holds.

This is an issue for the Windup project itself (the upstream project for RHAMT) - please file this at https://github.com/windup/windup
